media:
  input: assets/images
  output: /assets/images

content:
  - name: posts
    label: Blog Posts
    type: collection
    path: _posts
    format: frontmatter
    filename: "{year}-{month}-{day}-{slug}.md"
    # This list defines what you see in the CMS table view
    list:
      - title
      - date
    # These fields define what you edit in the CMS
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: cover_image
        label: Cover Image
        type: image
      - name: body
        label: Content
        type: markdown
        required: true